#!/bin/bash
#
# CHANGELOG Generator - Generate structured CHANGELOG.md from git history
# Usage: bash changelog.sh [repository_path] [output_file]
#
# Fetches commits since the last git tag and auto-categorizes them
# into: Added / Fixed / Changed / Removed
#

set -e

REPO_PATH="${1:-.}"
OUTPUT_FILE="${2:-CHANGELOG.md}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}CHANGELOG Generator${NC} - Generating from git history..."

cd "$REPO_PATH" || exit 1

# Check if it's a git repo
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo -e "${RED}Error: Not a git repository${NC}"
    exit 1
fi

# Get current version from last tag or use v0.0.0
LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
CURRENT_DATE=$(date +%Y-%m-%d)

# Get commits since last tag
COMMITS=$(git log "$LAST_TAG..HEAD" --pretty=format:"%s|||%b" 2>/dev/null || git log --all --pretty=format:"%s|||%b" -n 50)

# Initialize categories
ADDED=""
FIXED=""
CHANGED=""
REMOVED=""

# Parse commits and categorize
while IFS='|||' read -r msg body; do
    # Skip merge commits and initial commits
    [[ "$msg" =~ ^Merge ]] && continue
    [[ "$msg" =~ ^initial ]] && continue
    [[ -z "$msg" ]] && continue

    # Lowercase for matching
    lower_msg=$(echo "$msg" | tr '[:upper:]' '[:lower:]')

    # Categorize based on keywords
    if [[ "$lower_msg" =~ (add|new|feature|implement|create) ]]; then
        ADDED="${ADDED}- ${msg}\n"
    elif [[ "$lower_msg" =~ (fix|bug|resolve|repair|hotfix) ]]; then
        FIXED="${FIXED}- ${msg}\n"
    elif [[ "$lower_msg" =~ (update|change|modify|refactor|improve) ]]; then
        CHANGED="${CHANGED}- ${msg}\n"
    elif [[ "$lower_msg" =~ (remove|delete|deprecate|drop) ]]; then
        REMOVED="${REMOVED}- ${msg}\n"
    else
        # Default to Changed if no match
        CHANGED="${CHANGED}- ${msg}\n"
    fi
done <<< "$COMMITS"

# Build CHANGELOG content
{
    echo "# Changelog"
    echo ""
    echo "All notable changes to this project will be documented in this file."
    echo ""
    echo "The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),"
    echo "and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html)."
    echo ""
    echo "## [$CURRENT_DATE]"
    echo ""

    if [[ -n "$ADDED" ]]; then
        echo "### Added"
        echo ""
        echo -e "$ADDED"
    fi

    if [[ -n "$FIXED" ]]; then
        echo "### Fixed"
        echo ""
        echo -e "$FIXED"
    fi

    if [[ -n "$CHANGED" ]]; then
        echo "### Changed"
        echo ""
        echo -e "$CHANGED"
    fi

    if [[ -n "$REMOVED" ]]; then
        echo "### Removed"
        echo ""
        echo -e "$REMOVED"
    fi

    echo "---"
    echo ""
    echo "*Generated by changelog-generator.sh*"

} > "$OUTPUT_FILE"

echo -e "${GREEN}Success!${NC} CHANGELOG generated at: $OUTPUT_FILE"
echo ""
echo "Stats:"
[[ -n "$ADDED" ]] && echo "  Added: $(echo -e "$ADDED" | grep -c '^-' || echo 0)"
[[ -n "$FIXED" ]] && echo "  Fixed: $(echo -e "$FIXED" | grep -c '^-' || echo 0)"
[[ -n "$CHANGED" ]] && echo "  Changed: $(echo -e "$CHANGED" | grep -c '^-' || echo 0)"
[[ -n "$REMOVED" ]] && echo "  Removed: $(echo -e "$REMOVED" | grep -c '^-' || echo 0)"